### ISSUE TITLE
Add a link for ACSE-5 Practical about STL

### ISSUE THREAD

**Issue by acse-kx20** [acse-th119/ACSE_Recordings#1]
Adriana made an additional session about STL containers(vector, map, set and so on) on last Wednesday, which I think is useful for reviewing. Here is the link:
https://web.microsoftstream.com/video/31fecbea-82e4-4821-a90d-7281ce9d24c3
<img width="1026" alt="截屏2021-01-28 下午5 43 31" src="https://user-images.githubusercontent.com/72436082/106177919-0a8b8500-6191-11eb-843d-a8fb2dfa86ba.png">

**Comment by acse-th119** [comment]
Added it to the list! thank u
